
'use server';
/**
 * @fileOverview A Genkit flow to compose content for a project assignment notification.
 * The output is structured data intended for an email template.
 *
 * - generateAssignmentNotificationData - Generates structured data for the notification.
 * - AssignmentNotificationInput - Input type for the flow.
 * - AssignmentNotificationOutput - Output type for the flow (structured data).
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AssignmentNotificationInputSchema = z.object({
  userName: z.string().describe("The name of the user being assigned the project."),
  projectName: z.string().describe("The name of the project being assigned."),
  projectLocation: z.string().describe("The location/address of the project."),
  assignerName: z.string().describe("The name of the admin or supervisor assigning the project."),
  appName: z.string().default("SiteWise Reports").describe("The name of the application."),
});
export type AssignmentNotificationInput = z.infer<typeof AssignmentNotificationInputSchema>;

const AssignmentNotificationOutputSchema = z.object({
  emailSubject: z.string().describe("A concise subject line for the notification email, including the project name."),
  greeting: z.string().describe("A personalized greeting for the user, e.g., 'Hello [userName],'."),
  detailsIntro: z.string().describe("Introductory text for the project details, mentioning the assigner."),
  callToActionText: z.string().describe("Text for a call-to-action button/link, e.g., 'View Project Details in [appName]'."),
  closingText: z.string().describe("A friendly closing remark for the email."),
  // ProjectName, projectLocation, assignerName, appName are passed through from input for direct use in template
});
export type AssignmentNotificationOutput = z.infer<typeof AssignmentNotificationOutputSchema>;

export async function generateAssignmentNotificationData(
  input: AssignmentNotificationInput
): Promise<AssignmentNotificationOutput> {
  return assignmentNotificationFlow(input);
}

const assignmentNotificationPrompt = ai.definePrompt({
  name: 'assignmentNotificationDataPrompt',
  input: {schema: AssignmentNotificationInputSchema},
  output: {schema: AssignmentNotificationOutputSchema},
  prompt: `You are an assistant responsible for generating content for a project assignment notification email for the application "{{appName}}".
The user "{{userName}}" has been assigned to the project "{{projectName}}" (located at "{{projectLocation}}") by "{{assignerName}}".

Generate the following pieces of content for an email template:
1.  emailSubject: A clear and concise subject line indicating a new project assignment and mentioning the project name.
2.  greeting: A personalized and friendly greeting for the user.
3.  detailsIntro: A sentence introducing the project assignment and mentioning who assigned it ({{assignerName}}).
4.  callToActionText: Text for a call-to-action button or link, inviting the user to log in to {{appName}} for more details.
5.  closingText: A brief, friendly closing remark.

Ensure the tone is professional and encouraging.
The fields 'projectName', 'projectLocation', 'assignerName', and 'appName' will be available directly from the input to the email template, so you don't need to include them directly in these generated strings unless it's part of the natural language (like {{appName}} in callToActionText).
`,
});

const assignmentNotificationFlow = ai.defineFlow(
  {
    name: 'assignmentNotificationDataFlow',
    inputSchema: AssignmentNotificationInputSchema,
    outputSchema: AssignmentNotificationOutputSchema,
  },
  async input => {
    const {output} = await assignmentNotificationPrompt(input);
    // Combine LLM output with direct pass-through of some input fields
    // The schema for output already implies projectName, etc., will be part of it if included there.
    // Here, we ensure the LLM generates the dynamic text parts.
    return {
        ...output!, // Output from LLM as defined in AssignmentNotificationOutputSchema
        // If any fields from input should be directly in output and not generated by LLM, add them here.
        // For example, if projectName was NOT part of AssignmentNotificationOutputSchema, you'd add:
        // projectName: input.projectName,
        // But since they are defined in the output schema, the LLM is expected to provide them or they are passed if not in prompt.
        // The current prompt implies the LLM should focus on the text parts.
    };
  }
);
